'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import ThemeToggle from '@/components/ThemeToggle';
import { Sparkles, ArrowLeft, Calendar, Clock, BookOpen, User } from 'lucide-react';
import { supabase, isSupabaseConfigured } from '@/lib/supabase';

interface BlogPost {
  id: string;
  title: string;
  excerpt: string;
  content: string;
  date: string;
  readTime: string;
  category: string;
  author: string;
}

export default function BlogHub() {
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [selectedPost, setSelectedPost] = useState<BlogPost | null>(null);

  useEffect(() => {
    const checkSession = async () => {
      const demoSession = localStorage.getItem('demo-session');
      if (demoSession) {
        setIsLoggedIn(true);
        return;
      }
      if (isSupabaseConfigured()) {
        const { data: { session } } = await supabase.auth.getSession();
        if (session) {
          setIsLoggedIn(true);
        }
      }
    };
    checkSession();
  }, []);

  const blogPosts: BlogPost[] = [
    {
      id: 'post-1',
      title: 'The Shift to Autonomous Content Pipelines: Why n8n and LLMs are Replacing Manual Scripting',
      excerpt: 'Traditional short-form editing is slow. Learn how autonomous orchestration suites are automating the trend-to-script workflow.',
      date: 'Aug 18, 2026',
      readTime: '5 min read',
      category: 'Agentic AI',
      author: 'ViralFlow Tech Team',
      content: `The media production landscape is experiencing a paradigm shift. For years, creators relied on manual workflows: scrubbing YouTube for trending topics, writing video scripts in google docs, recording raw audio voiceovers, finding b-roll overlays, and manually cropping videos in Premier Pro.

This process is slow, resource-heavy, and non-scalable.

### Enter Autonomous Orchestration
By utilizing n8n workflows and LLMs like Google Gemini 1.5 Pro, creators can build an always-on content engine:
1. **Trend Scrapers**: Run on scheduled triggers (e.g. every 30 minutes) to query API parameters, checking YouTube searches and tech RSS feeds for viral topics.
2. **Context-Aware LLM Generators**: Instead of generic prompts, the Script Agent reads a custom "Creator DNA profile" (voice, tones, rules) and writes structured scenes directly in JSON format.
3. **Automated Renders**: Webhooks dispatch the timeline instructions directly to FastAPI render workers, where audio layers and video cuts compile programmatically.

The results are striking: a production pipeline that shrinks lead times from 6 hours to 90 seconds, all while respecting the creator's voice.`
    },
    {
      id: 'post-2',
      title: 'Cloning Your Voice Safely: Best Practices with ElevenLabs and Voice DNA',
      excerpt: 'Voice cloning is a core pillar of modern content automation. Here is how to configure safety guard rails and secure your output.',
      date: 'Aug 15, 2026',
      readTime: '4 min read',
      category: 'Audio Synthesis',
      author: 'Acoustic Labs',
      content: `Synthetic speech has evolved from robotic text-to-speech to human-like cloned speech. By using tools like ElevenLabs Multilingual v2, autonomous agents can speak with the exact timbre, modulation, and accent of a creator.

However, voice cloning requires deep control and strict compliance parameters.

### Safeguarding Voice Assets
1. **Boundary Enforcement**: In the Creator DNA profile, the creator should establish strict "topics to avoid" (e.g., medical claims, financial recommendations, political opinions).
2. **Dynamic Fact-Checking**: Before the script is submitted to ElevenLabs, an independent auditor node inside n8n must analyze the script for numerical claims or guarantees, flagging risky content for manual approval.
3. **Session Expiry**: Ensure that rendering workers only process audio jobs generated by authenticated dashboard user tokens, preventing unauthorized voice generations.`
    },
    {
      id: 'post-3',
      title: 'Fact-Checking at Scale: Implementing Automated Verifications inside LLM Outputs',
      excerpt: 'How to construct structured JSON schemas and secondary auditor nodes to prevent hallucinations in automated scripts.',
      date: 'Aug 12, 2026',
      readTime: '6 min read',
      category: 'Integrity & Quality',
      author: 'Data Integrity Group',
      content: `LLM hallucinations are a major challenge in automated content pipelines. If an autonomous script agent generates inaccurate statistics or fabricates facts, it damages the creator's brand and authority.

To solve this, modern pipelines implement **Multi-Agent Verification Loops**.

### The Fact-Check Architecture
Rather than trusting the initial script draft, the n8n orchestrator triggers a secondary verification workflow:
1. **Claims Extraction**: A secondary LLM node parses the script and extracts all verifiable claims into an array (e.g., "Company X grew by 40%").
2. **Verification Searches**: The orchestrator triggers Google Search API nodes to look up external sources verifying the claim.
3. **Opportunity Grader**: The claims are scored: Verified, Unverified, or Risky. If any claim is marked as Risky, the rendering job is paused and routed to the Creator's Approval Queue inside the dashboard, giving humans the final edit control.`
    }
  ];

  return (
    <div style={{
      minHeight: '100vh',
      width: '100%',
      backgroundColor: 'var(--bg-base)',
      color: 'var(--text-primary)',
      display: 'flex',
      flexDirection: 'column',
      position: 'relative',
      fontFamily: 'var(--font-body)'
    }}>
      {/* Navigation Header */}
      <header style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: '24px 40px',
        maxWidth: '1200px',
        width: '100%',
        margin: '0 auto',
        zIndex: 10
      }}>
        <Link href="/" style={{
          display: 'flex',
          alignItems: 'center',
          gap: '10px',
          color: 'var(--accent-primary)',
          fontSize: '1.5rem',
          fontWeight: 800,
          fontFamily: 'var(--font-heading)'
        }}>
          <Sparkles size={24} />
          <span>ViralFlow AI</span>
        </Link>
        
        <div style={{ display: 'flex', alignItems: 'center', gap: '20px' }}>
          <Link href="/" style={{
            fontSize: '0.9rem',
            fontWeight: 600,
            color: 'var(--text-secondary)',
            transition: 'color var(--transition-fast)'
          }}
          onMouseEnter={(e) => e.currentTarget.style.color = 'var(--text-primary)'}
          onMouseLeave={(e) => e.currentTarget.style.color = 'var(--text-secondary)'}
          >
            Back to Home
          </Link>
          <Link href={isLoggedIn ? "/dashboard" : "/signup"} style={{
            padding: '10px 20px',
            borderRadius: 'var(--radius-sm)',
            backgroundColor: 'var(--accent-primary)',
            color: '#ffffff',
            fontSize: '0.9rem',
            fontWeight: 600,
            boxShadow: 'var(--shadow-glow)',
            transition: 'background-color var(--transition-fast)'
          }}
          onMouseEnter={(e) => e.currentTarget.style.backgroundColor = 'var(--accent-primary-hover)'}
          onMouseLeave={(e) => e.currentTarget.style.backgroundColor = 'var(--accent-primary)'}
          >
            Launch Studio
          </Link>
          <ThemeToggle />
        </div>
      </header>

      {/* Main Container */}
      <main style={{
        maxWidth: '900px',
        width: '100%',
        margin: '0 auto',
        padding: '60px 24px',
        flex: 1
      }}>
        {/* Page Header */}
        <div style={{ textAlign: 'center', marginBottom: '60px' }}>
          <h1 style={{
            fontSize: '3rem',
            fontFamily: 'var(--font-heading)',
            fontWeight: 800,
            marginBottom: '16px'
          }}>
            ViralFlow Insights
          </h1>
          <p style={{ color: 'var(--text-secondary)', fontSize: '1.15rem', maxWidth: '600px', margin: '0 auto' }}>
            In-depth guides on autonomous n8n orchestration, voice synthesis safety, and Remotion rendering pipelines.
          </p>
        </div>

        {/* Blog Post Grid */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '32px' }}>
          {blogPosts.map(post => (
            <article 
              key={post.id}
              className="glass-panel"
              style={{
                padding: '36px',
                borderRadius: 'var(--radius-lg)',
                border: '1px solid var(--border-color)',
                display: 'flex',
                flexDirection: 'column',
                gap: '16px',
                cursor: 'pointer',
                transition: 'border-color var(--transition-fast)'
              }}
              onClick={() => setSelectedPost(post)}
              onMouseEnter={(e) => e.currentTarget.style.borderColor = 'var(--accent-primary)'}
              onMouseLeave={(e) => e.currentTarget.style.borderColor = 'var(--border-color)'}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: '16px', fontSize: '0.8rem', color: 'var(--text-secondary)' }}>
                <span style={{ backgroundColor: 'var(--accent-glow)', color: 'var(--accent-primary)', padding: '4px 10px', borderRadius: 'var(--radius-full)', fontWeight: 700, textTransform: 'uppercase' }}>
                  {post.category}
                </span>
                <span style={{ display: 'flex', alignItems: 'center', gap: '4px' }}><Calendar size={12} /> {post.date}</span>
                <span style={{ display: 'flex', alignItems: 'center', gap: '4px' }}><Clock size={12} /> {post.readTime}</span>
              </div>

              <h2 style={{ fontSize: '1.5rem', fontWeight: 800, fontFamily: 'var(--font-heading)' }}>
                {post.title}
              </h2>
              
              <p style={{ color: 'var(--text-secondary)', lineHeight: '1.6', fontSize: '0.95rem' }}>
                {post.excerpt}
              </p>

              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: '8px' }}>
                <span style={{ fontSize: '0.85rem', color: 'var(--text-muted)', display: 'flex', alignItems: 'center', gap: '6px' }}>
                  <User size={14} /> By {post.author}
                </span>
                <span style={{ fontWeight: 600, fontSize: '0.9rem', color: 'var(--accent-primary)', display: 'flex', alignItems: 'center', gap: '4px' }}>
                  Read Article &rarr;
                </span>
              </div>
            </article>
          ))}
        </div>
      </main>

      {/* Reader Modal */}
      {selectedPost && (
        <div style={{
          position: 'fixed',
          inset: 0,
          backgroundColor: 'rgba(0, 0, 0, 0.75)',
          backdropFilter: 'blur(8px)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          zIndex: 100,
          padding: '24px'
        }}>
          <div className="glass-panel" style={{
            width: '100%',
            maxWidth: '750px',
            borderRadius: 'var(--radius-lg)',
            padding: '40px',
            maxHeight: '85vh',
            overflowY: 'auto',
            boxShadow: 'var(--shadow-lg)',
            display: 'flex',
            flexDirection: 'column',
            gap: '24px'
          }}>
            <button 
              onClick={() => setSelectedPost(null)}
              style={{
                alignSelf: 'flex-start',
                display: 'flex',
                alignItems: 'center',
                gap: '8px',
                fontSize: '0.85rem',
                fontWeight: 600,
                color: 'var(--text-secondary)',
                backgroundColor: 'transparent',
                border: 'none',
                cursor: 'pointer'
              }}
            >
              <ArrowLeft size={16} /> Back to Blog List
            </button>

            <div>
              <div style={{ display: 'flex', alignItems: 'center', gap: '16px', fontSize: '0.8rem', color: 'var(--text-muted)', marginBottom: '12px' }}>
                <span style={{ backgroundColor: 'var(--accent-glow)', color: 'var(--accent-primary)', padding: '4px 10px', borderRadius: 'var(--radius-full)', fontWeight: 700, textTransform: 'uppercase' }}>
                  {selectedPost.category}
                </span>
                <span>{selectedPost.date}</span>
                <span>{selectedPost.readTime}</span>
              </div>
              <h2 style={{ fontSize: '2rem', fontFamily: 'var(--font-heading)', fontWeight: 800, lineHeight: '1.25' }}>
                {selectedPost.title}
              </h2>
              <div style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginTop: '8px', display: 'flex', alignItems: 'center', gap: '6px' }}>
                <User size={14} /> Published by {selectedPost.author}
              </div>
            </div>

            <hr style={{ border: '0', borderTop: '1px solid var(--border-color)', margin: '0' }} />

            <div 
              style={{
                color: 'var(--text-secondary)',
                lineHeight: '1.75',
                fontSize: '1rem',
                display: 'flex',
                flexDirection: 'column',
                gap: '16px',
                whiteSpace: 'pre-line'
              }}
            >
              {selectedPost.content}
            </div>

            <button
              onClick={() => setSelectedPost(null)}
              style={{
                width: '100%',
                padding: '12px',
                borderRadius: 'var(--radius-sm)',
                backgroundColor: 'var(--accent-primary)',
                color: '#ffffff',
                fontWeight: 600,
                cursor: 'pointer',
                textAlign: 'center',
                marginTop: '16px'
              }}
            >
              Done Reading
            </button>
          </div>
        </div>
      )}

      {/* Footer */}
      <footer style={{
        marginTop: 'auto',
        borderTop: '1px solid var(--border-color)',
        padding: '32px 40px',
        backgroundColor: 'var(--bg-surface)'
      }}>
        <div style={{
          maxWidth: '1200px',
          width: '100%',
          margin: '0 auto',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          flexWrap: 'wrap',
          gap: '16px'
        }} className="landing-footer-container">
          <span style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>
            &copy; 2026 ViralFlow AI. All rights reserved.
          </span>
          <div style={{ display: 'flex', gap: '24px', fontSize: '0.85rem', color: 'var(--text-secondary)' }}>
            <Link href="/" style={{ transition: 'color var(--transition-fast)' }}>
              Home
            </Link>
            <Link href="/login" style={{ transition: 'color var(--transition-fast)' }}>
              Creator Log In
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
