'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import ThemeToggle from '@/components/ThemeToggle';
import CyberTiltCard from '@/components/CyberTiltCard';
import { Sparkles, ArrowLeft, Calendar, Clock, BookOpen, User, Terminal } from 'lucide-react';
import { supabase, isSupabaseConfigured } from '@/lib/supabase';

interface BlogPost {
  id: string;
  title: string;
  excerpt: string;
  content: string;
  date: string;
  readTime: string;
  category: string;
  author: string;
}

export default function BlogHub() {
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [selectedPost, setSelectedPost] = useState<BlogPost | null>(null);

  useEffect(() => {
    const checkSession = async () => {
      const demoSession = localStorage.getItem('demo-session');
      if (demoSession) {
        setIsLoggedIn(true);
        return;
      }
      if (isSupabaseConfigured()) {
        const { data: { session } } = await supabase.auth.getSession();
        if (session) {
          setIsLoggedIn(true);
        }
      }
    };
    checkSession();
  }, []);

  const blogPosts: BlogPost[] = [
    {
      id: 'post-1',
      title: 'The Shift to Autonomous Content Pipelines: Why n8n and LLMs are Replacing Manual Scripting',
      excerpt: 'Traditional short-form editing is slow. Learn how autonomous orchestration suites are automating the trend-to-script workflow.',
      date: 'Aug 18, 2026',
      readTime: '5 min read',
      category: 'Agentic AI',
      author: 'ViralFlow Tech Team',
      content: `The media production landscape is experiencing a paradigm shift. For years, creators relied on manual workflows: scrubbing YouTube for trending topics, writing video scripts in google docs, recording raw audio voiceovers, finding b-roll overlays, and manually cropping videos in Premier Pro.

This process is slow, resource-heavy, and non-scalable.

### Enter Autonomous Orchestration
By utilizing n8n workflows and LLMs like Google Gemini 1.5 Pro, creators can build an always-on content engine:
1. **Trend Scrapers**: Run on scheduled triggers (e.g. every 30 minutes) to query API parameters, checking YouTube searches and tech RSS feeds for viral topics.
2. **Context-Aware LLM Generators**: Instead of generic prompts, the Script Agent reads a custom "Creator DNA profile" (voice, tones, rules) and writes structured scenes directly in JSON format.
3. **Automated Renders**: Webhooks dispatch the timeline instructions directly to FastAPI render workers, where audio layers and video cuts compile programmatically.

The results are striking: a production pipeline that shrinks lead times from 6 hours to 90 seconds, all while respecting the creator's voice.`
    },
    {
      id: 'post-2',
      title: 'Cloning Your Voice Safely: Best Practices with ElevenLabs and Voice DNA',
      excerpt: 'Voice cloning is a core pillar of modern content automation. Here is how to configure safety guard rails and secure your output.',
      date: 'Aug 15, 2026',
      readTime: '4 min read',
      category: 'Audio Synthesis',
      author: 'Acoustic Labs',
      content: `Synthetic speech has evolved from robotic text-to-speech to human-like cloned speech. By using tools like ElevenLabs Multilingual v2, autonomous agents can speak with the exact timbre, modulation, and accent of a creator.

However, voice cloning requires deep control and strict compliance parameters.

### Safeguarding Voice Assets
1. **Boundary Enforcement**: In the Creator DNA profile, the creator should establish strict "topics to avoid" (e.g., medical claims, financial recommendations, political opinions).
2. **Dynamic Fact-Checking**: Before the script is submitted to ElevenLabs, an independent auditor node inside n8n must analyze the script for numerical claims or guarantees, flagging risky content for manual approval.
3. **Session Expiry**: Ensure that rendering workers only process audio jobs generated by authenticated dashboard user tokens, preventing unauthorized voice generations.`
    },
    {
      id: 'post-3',
      title: 'Fact-Checking at Scale: Implementing Automated Verifications inside LLM Outputs',
      excerpt: 'How to construct structured JSON schemas and secondary auditor nodes to prevent hallucinations in automated scripts.',
      date: 'Aug 12, 2026',
      readTime: '6 min read',
      category: 'Integrity & Quality',
      author: 'Data Integrity Group',
      content: `LLM hallucinations are a major challenge in automated content pipelines. If an autonomous script agent generates inaccurate statistics or fabricates facts, it damages the creator's brand and authority.

To solve this, modern pipelines implement **Multi-Agent Verification Loops**.

### The Fact-Check Architecture
Rather than trusting the initial script draft, the n8n orchestrator triggers a secondary verification workflow:
1. **Claims Extraction**: A secondary LLM node parses the script and extracts all verifiable claims into an array (e.g., "Company X grew by 40%").
2. **Verification Searches**: The orchestrator triggers Google Search API nodes to look up external sources verifying the claim.
3. **Opportunity Grader**: The claims are scored: Verified, Unverified, or Risky. If any claim is marked as Risky, the rendering job is paused and routed to the Creator's Approval Queue inside the dashboard, giving humans the final edit control.`
    }
  ];

  return (
    <div style={{
      minHeight: '100vh',
      width: '100%',
      backgroundColor: 'var(--bg-base)',
      color: 'var(--text-primary)',
      display: 'flex',
      flexDirection: 'column',
      position: 'relative'
    }}>
      {/* Cyber Navigation Header */}
      <header style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: '16px 32px',
        maxWidth: '1280px',
        width: '100%',
        margin: '16px auto 0 auto',
        zIndex: 10,
        backgroundColor: 'var(--bg-surface-translucent)',
        border: '3px solid var(--border-color)',
        boxShadow: '4px 4px 0px #00f0ff',
        borderRadius: 'var(--radius-md)'
      }}>
        <Link href="/" style={{
          display: 'flex',
          alignItems: 'center',
          gap: '12px',
          color: 'var(--accent-primary)',
          fontSize: '1.4rem',
          fontWeight: 800,
          fontFamily: 'var(--font-heading)'
        }}>
          <div style={{ padding: '6px', backgroundColor: '#020204', border: '2px solid var(--accent-primary)', color: 'var(--accent-primary)', display: 'flex' }}>
            <Sparkles size={20} />
          </div>
          <span>VIRALFLOW.AI</span>
        </Link>
        
        <div style={{ display: 'flex', alignItems: 'center', gap: '20px' }}>
          <Link href="/" style={{ fontSize: '0.85rem', fontFamily: 'var(--font-mono)', fontWeight: 700, color: 'var(--text-secondary)', textTransform: 'uppercase' }}>
            [HOME]
          </Link>
          <Link href={isLoggedIn ? "/dashboard" : "/signup"} className="cyber-btn-primary" style={{ padding: '8px 16px', fontSize: '0.85rem' }}>
            LAUNCH STUDIO
          </Link>
          <ThemeToggle />
        </div>
      </header>

      {/* Main Container */}
      <main style={{
        maxWidth: '1000px',
        width: '100%',
        margin: '0 auto',
        padding: '60px 24px',
        flex: 1
      }}>
        {/* Page Header */}
        <div style={{ textAlign: 'center', marginBottom: '60px' }}>
          <div className="cyber-badge" style={{ marginBottom: '16px' }}>INTEL & ENGINEERING INSIGHTS</div>
          <h1 style={{
            fontSize: '3.5rem',
            fontFamily: 'var(--font-heading)',
            fontWeight: 800,
            textTransform: 'uppercase',
            marginBottom: '16px'
          }}>
            CYBER-AGENTIC INSIGHTS
          </h1>
          <p style={{ color: 'var(--text-secondary)', fontFamily: 'var(--font-mono)', fontSize: '0.95rem', maxWidth: '650px', margin: '0 auto' }}>
            [DEEP DIVES ON N8N ORCHESTRATION, VOICE DNA SAFETY, AND FFMPEG RENDERING WORKERS]
          </p>
        </div>

        {/* Cyber Blog Post Grid with 3D Tilt Cards */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '32px' }}>
          {blogPosts.map((post, idx) => (
            <div key={post.id} onClick={() => setSelectedPost(post)}>
              <CyberTiltCard borderColor={idx === 0 ? 'cyan' : idx === 1 ? 'lime' : 'pink'} style={{ padding: '36px' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '16px', fontSize: '0.8rem', fontFamily: 'var(--font-mono)', color: 'var(--text-secondary)', marginBottom: '12px' }}>
                  <span className="cyber-badge" style={{
                    borderColor: idx === 0 ? 'var(--accent-primary)' : idx === 1 ? 'var(--accent-secondary)' : 'var(--accent-pink)',
                    color: idx === 0 ? 'var(--accent-primary)' : idx === 1 ? 'var(--accent-secondary)' : 'var(--accent-pink)'
                  }}>
                    [{post.category.toUpperCase()}]
                  </span>
                  <span style={{ display: 'flex', alignItems: 'center', gap: '4px' }}><Calendar size={12} /> {post.date}</span>
                  <span style={{ display: 'flex', alignItems: 'center', gap: '4px' }}><Clock size={12} /> {post.readTime}</span>
                </div>

                <h2 style={{ fontSize: '1.65rem', fontWeight: 800, fontFamily: 'var(--font-heading)', marginBottom: '12px', textTransform: 'uppercase' }}>
                  {post.title}
                </h2>
                
                <p style={{ color: 'var(--text-secondary)', lineHeight: '1.6', fontSize: '0.95rem', marginBottom: '20px' }}>
                  {post.excerpt}
                </p>

                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <span style={{ fontSize: '0.85rem', fontFamily: 'var(--font-mono)', color: 'var(--text-muted)', display: 'flex', alignItems: 'center', gap: '6px' }}>
                    <User size={14} /> AUTHOR: {post.author.toUpperCase()}
                  </span>
                  <span style={{ fontWeight: 800, fontFamily: 'var(--font-mono)', fontSize: '0.85rem', color: 'var(--accent-primary)', display: 'flex', alignItems: 'center', gap: '4px' }}>
                    READ TRANSMISSION &rarr;
                  </span>
                </div>
              </CyberTiltCard>
            </div>
          ))}
        </div>
      </main>

      {/* Cyber Terminal Reader Drawer Modal */}
      {selectedPost && (
        <div style={{
          position: 'fixed',
          inset: 0,
          backgroundColor: 'rgba(2, 2, 4, 0.85)',
          backdropFilter: 'blur(8px)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          zIndex: 100,
          padding: '24px'
        }}>
          <CyberTiltCard borderColor="cyan" style={{
            width: '100%',
            maxWidth: '800px',
            padding: '40px',
            maxHeight: '85vh',
            overflowY: 'auto',
            display: 'flex',
            flexDirection: 'column',
            gap: '24px'
          }}>
            <button 
              onClick={() => setSelectedPost(null)}
              style={{
                alignSelf: 'flex-start',
                display: 'flex',
                alignItems: 'center',
                gap: '8px',
                fontSize: '0.85rem',
                fontFamily: 'var(--font-mono)',
                fontWeight: 700,
                color: 'var(--accent-primary)',
                cursor: 'pointer'
              }}
            >
              <ArrowLeft size={16} /> [RETURN TO TRANSMISSIONS]
            </button>

            <div>
              <div style={{ display: 'flex', alignItems: 'center', gap: '16px', fontSize: '0.8rem', fontFamily: 'var(--font-mono)', color: 'var(--text-muted)', marginBottom: '12px' }}>
                <span className="cyber-badge">[{selectedPost.category.toUpperCase()}]</span>
                <span>{selectedPost.date}</span>
                <span>{selectedPost.readTime}</span>
              </div>
              <h2 style={{ fontSize: '2rem', fontFamily: 'var(--font-heading)', fontWeight: 800, lineHeight: '1.2', textTransform: 'uppercase' }}>
                {selectedPost.title}
              </h2>
              <div style={{ fontSize: '0.85rem', fontFamily: 'var(--font-mono)', color: 'var(--text-muted)', marginTop: '8px', display: 'flex', alignItems: 'center', gap: '6px' }}>
                <User size={14} /> AUTHOR: {selectedPost.author.toUpperCase()}
              </div>
            </div>

            <hr style={{ border: '0', borderTop: '2px solid var(--border-color)', margin: '0' }} />

            <div 
              style={{
                color: 'var(--text-secondary)',
                lineHeight: '1.75',
                fontSize: '1rem',
                display: 'flex',
                flexDirection: 'column',
                gap: '16px',
                whiteSpace: 'pre-line'
              }}
            >
              {selectedPost.content}
            </div>

            <button
              onClick={() => setSelectedPost(null)}
              className="cyber-btn-primary"
              style={{ width: '100%', marginTop: '16px' }}
            >
              CLOSE TRANSMISSION
            </button>
          </CyberTiltCard>
        </div>
      )}

      {/* Cyber Footer */}
      <footer style={{
        marginTop: 'auto',
        borderTop: '3px solid var(--border-color)',
        padding: '32px 40px',
        backgroundColor: 'var(--bg-surface)'
      }}>
        <div style={{
          maxWidth: '1280px',
          width: '100%',
          margin: '0 auto',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          flexWrap: 'wrap',
          gap: '16px'
        }}>
          <span style={{ fontSize: '0.85rem', fontFamily: 'var(--font-mono)', color: 'var(--text-muted)' }}>
            &copy; 2026 VIRALFLOW AI. CYBER-BRUTALIST ARCHITECTURE.
          </span>
          <div style={{ display: 'flex', gap: '24px', fontSize: '0.85rem', fontFamily: 'var(--font-mono)', color: 'var(--accent-primary)' }}>
            <Link href="/" style={{ textTransform: 'uppercase' }}>
              [HOME]
            </Link>
            <Link href="/login" style={{ textTransform: 'uppercase' }}>
              [CREATOR LOG IN]
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
